{% set version = '0.1.10' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-dunlin
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/dunlin_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/dunlin/dunlin_{{ version }}.tar.gz
  sha256: d32c83fc3350aceaabaa5337e5a671e0125d1633fa30f26d534b4b655998ed08

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-checkmate >=2.1.0
    - r-dplyr >=1.1.0
    - r-forcats >=1.0.0
    - r-glue >=1.0.0
    - r-magrittr >=1.5
    - r-rlang >=1.0.0
    - r-stringr >=1.4.1
    - r-tibble >=1.2
    - r-yaml >=2.1.15
  run:
    - r-base
    - r-checkmate >=2.1.0
    - r-dplyr >=1.1.0
    - r-forcats >=1.0.0
    - r-glue >=1.0.0
    - r-magrittr >=1.5
    - r-rlang >=1.0.0
    - r-stringr >=1.4.1
    - r-tibble >=1.2
    - r-yaml >=2.1.15

test:
  commands:
    - $R -e "library('dunlin')"           # [not win]
    - "\"%R%\" -e \"library('dunlin')\""  # [win]

about:
  home: https://insightsengineering.github.io/dunlin/, https://github.com/insightsengineering/dunlin/
  license: Apache-2.0
  summary: A collection of functions to preprocess data and organize them in a format amenable
    to use by chevron.
  license_family: APACHE
  license_file:
    - LICENSE-2.0.txt

extra:
  recipe-maintainers:
    - conda-forge/r
